#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/RefreshView/refreshview 80
    chown root /opt/RefreshView/chrome-sandbox
    chmod 4755 /opt/RefreshView/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser refreshview.desktop && sudo update-alternatives --config x-www-browser to set RefreshView as your default browser."
    ln -sf /opt/RefreshView/refreshview /usr/bin/refreshview
fi
